- name: launch an instance on OpenStack
  os_server:
    state: present
    auth:
      auth_url: "{{ openstack_auth_url }}"
      username: "{{ openstack_username }}"
      password: "{{ openstack_password }}"
      project_name: "{{ openstack_project }}"
      domain_name: "{{ openstack_domain | default('default') }}"
    name: "{{ item }}"
    region_name: "{{ openstack_region | default('RegionOne') }}"
    availability_zone: "{{ openstack_availability_zone | default('nova') }}"
    image: "{{ openstack_image_id }}"
    key_name: "{{ openstack_key_pair }}"
    timeout: 200
    flavor: "{{ openstack_flavor }}"
    security_groups: "{{ openstack_security_groups | default('default') }}"
    meta: 
      hostname: "{{ item }}"
    nics:
      - net-id: "{{ openstack_nic_ids }}"
