- name: delete the instance on OpenStack
  os_server:
    state: absent
    auth:
      auth_url: "{{ openstack_auth_url }}"
      username: "{{ openstack_username }}"
      password: "{{ openstack_password }}"
      project_name: "{{ openstack_project }}"
      domain_name: "{{ openstack_domain | default('default') }}"
    name: "{{ item }}"
    region_name: "{{ openstack_region | default('RegionOne') }}"
    availability_zone: "{{ openstack_availability_zone | default('nova') }}"
    delete_fip: yes
